from sqlalchemy.orm import Session
from uuid import uuid4
from app.repositories.hospital_repo import HospitalRepository
from app.schemas.hospital import HospitalCreate

class HospitalService:
    def __init__(self, db: Session):
        self.db = db
        self.repo = HospitalRepository(db)

    def create_hospital(self, hospital_data: HospitalCreate):
        # Check if hospital with same name exists
        existing = self.repo.get_by_name(hospital_data.name)
        if existing:
            raise ValueError("Hospital with this name already exists")

        # Create new hospital – id is generated by the model default, so we don't pass it
        return self.repo.create(
            name=hospital_data.name,
            district=hospital_data.district,
            address=hospital_data.address,
            phone=hospital_data.phone,
            email=hospital_data.email
        )

    def get_all_hospitals(self):
        return self.repo.list_all()